name: warga_kita_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1

  cupertino_icons: ^1.0.8
  intl_phone_number_input: ^0.7.5
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

    - assets/images/logo.png
    - assets/images/logo+name.png
    - assets/images/texture.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
